name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter
        ##TODO
        run: echo "Using maven-checkstyle-plugin during 'validate' phase"

      - name: Run Checkstyle
        ##TODO
        run: mvn -B -e -DskipTests=false validate

      - name: Upload Checkstyle Result
        ##TODO
        uses: actions/upload-artifact@v4
        with:
            name: checkstyle-report
            path: target/site/checkstyle.xml
            if-no-files-found: warn

      - name: Run Maven Test
        ##TODO
        run: mvn -B -e test

      - name: Jacoco Report
        ##TODO
        uses: actions/upload-artifact@v4
        with:
            name: jacoco-report
            path: |
              target/site/jacoco/jacoco.xml
              target/site/jacoco/index.html
            if-no-files-found: warn